name: ygo_companion
description: A companion app for Yu-Gi-Oh! players.
version: 0.1.0

publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^0.5.6+3
  provider: ^3.1.0
  math_expressions: ^2.0.0
  firebase_admob: ^0.9.3+2
  device_id: ^0.2.0
  flutter_styled_toast: ^1.3.1
  url_launcher: ^5.4.10

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.4"

flutter_icons:
  # To generate logo, `flutter pub run flutter_launcher_icons:main`
  # Generate logo from https://romannurik.github.io/AndroidAssetStudio/icons-launcher.html
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo/ic_launcher.png"
  adaptive_icon_foreground: "assets/logo/ic_launcher.png"
  adaptive_icon_background: "assets/logo/ic_launcher_background.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/calculator/
    - assets/logo/yutopia_logo.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Customicons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: DiceIcons
      fonts:
        - asset: assets/fonts/DiceIcons.ttf
