/// Flutter icons DiceIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DiceIcons
///      fonts:
///       - asset: fonts/DiceIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class DiceIcons {
  DiceIcons._();

  static const _kFontFam = 'DiceIcons';
  static const _kFontPkg = null;

  static const IconData dice1 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice2 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice3 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice4 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice5 = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice6 = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
